server:
  port: 7709

spring:
  application:
    name: eureka-config-client

eureka:
  instance:
    instance-id: eureka-config-client1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server-9001.com:9001/eureka/