server:
  port: 7701

spring:
  application:
    name: eureka-config-client

eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server-9001.com:9001/eureka/

source: 
  client: 
    name: config-dev
